# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml

# This is a sample GitLab CI/CD configuration file that should run without any modifications.
# It demonstrates a basic 3 stage CI/CD pipeline. Instead of real tests or scripts,
# it uses echo commands to simulate the pipeline execution.
#
# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages
default:
  tags:
    - docker

stages:          # List of stages for jobs, and their order of execution
  - build
  - test

.apt_dependencies: &apt_dependencies
  - echo "Installing dependencies..."
  - apt update
  - apt install -y --no-install-recommends g++ make cmake libssl-dev libpng-dev libcap2-bin clang-tidy
  - echo "Installing dependencies complete."

.build_step: &build_step
  - echo "Compiling the code..."
  - mkdir build
  - cd build
  - cmake ..
  - make -j$(nproc)
  - setcap cap_net_raw+ep pingo
  - echo "Compile complete."

build-debian:
  stage: build
  image: debian:latest
  tags:
    - x86_64
  script:
    - *apt_dependencies
    - *build_step
  artifacts:
    paths:
      - /builds/edward/pingo/build/pingo

build-debian-arm64:
  stage: build
  image: debian:latest
  tags:
    - arm64
  script:
    - *apt_dependencies
    - *build_step
  artifacts:
    paths:
      - /builds/edward/pingo/build/pingo

build-ubuntu:
  stage: build
  image: ubuntu:latest
  script:
    - *apt_dependencies
    - *build_step
  artifacts:
    paths:
      - /builds/edward/pingo/build/pingo


build-fedora:
  stage: build
  image: fedora:latest
  script:
    - echo "Installing dependencies..."
    - dnf install -y gcc-c++ cmake openssl-devel libpng-devel clang-tools-extra
    - echo "Installing dependencies complete."
    - *build_step
  artifacts:
    paths:
      - /builds/edward/pingo/build/pingo

include:
  - template: Security/SAST.gitlab-ci.yml